name: Build Angular and Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Construir o projeto Angular
        run: npm run build -- --configuration=production

      - name: Armazenar build como artefato
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/
          retention-days: 7
