name: Build and Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar ambiente para Java
        if: contains(matrix.language, 'java')
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar ambiente para Node.js
        if: contains(matrix.language, 'node')
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências e compilar (Java)
        if: contains(matrix.language, 'java')
        run: |
          mvn clean package
          mkdir -p artifacts
          cp target/*.jar artifacts/

      - name: Instalar dependências e empacotar (Node.js)
        if: contains(matrix.language, 'node')
        run: |
          npm install
          mkdir -p artifacts
          zip -r artifacts/app.zip .

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: artifacts/
